### ISSUE TITLE
Error when printing table for experiments

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/autotune#51]
An error occurs when printing an experiment for an app:

```bash
$ tune ls 8a77a2d6-326f-463e-baf8-ddcef1262016
...
TypeError: Cannot set property '0' of undefined
    at chunkedValue.forEach (/usr/local/lib/node_modules/autotune/node_modules/table/dist/mapDataUsingRowHeightIndex.js:49:35)
    at Array.forEach (<anonymous>)
    at cells.forEach (/usr/local/lib/node_modules/autotune/node_modules/table/dist/mapDataUsingRowHeightIndex.js:48:20)
    at Array.forEach (<anonymous>)
    at unmappedRows.map (/usr/local/lib/node_modules/autotune/node_modules/table/dist/mapDataUsingRowHeightIndex.js:39:11)
    at Array.map (<anonymous>)
    at exports.default (/usr/local/lib/node_modules/autotune/node_modules/table/dist/mapDataUsingRowHeightIndex.js:30:35)
    at Object.exports.default [as table] (/usr/local/lib/node_modules/autotune/node_modules/table/dist/table.js:126:51)
    at logTable (/usr/local/lib/node_modules/autotune/dist/cli/index.js:508:25)
    at /usr/local/lib/node_modules/autotune/dist/cli/index.js:372:25
```

**Comment by schani** [comment]
That's due to this bug: https://github.com/chalk/slice-ansi/pull/19

I'll do a workaround because I don't want to wait until upstream is updated.

**Comment by schani** [comment]
The workaround is to set `truncate` in the column configuration, which gives us something like this:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/61363/42519658-65f9ca30-8419-11e8-9945-ecbbe71b6fce.png">
